#ifndef _vca_xmlcfgdef_h_

#define _vca_xmlcfgdef_h_

#define _TAG_ROOT		"Root"
#define _TAG_SCHEMAVERSION	"schema_version"
#define _XMLTAG_ROOT		"<Root>"
#define _XMLTAG_ROOT_		"</Root>"

// XML Tags for Channel Settings
#define _TAG_CHANNELSETTINGS		"ChannelSettings"
#define _TAG_CHANNEL_ENABLE		"Enable"
#define _TAG_CHANNEL_ENABLESTB		"EnableStb"
#define _TAG_CHANNEL_ENABLEABOBJ	"EnableAbObj"
#define _TAG_CHANNEL_ENABLEMOVOBJ	"EnableMovObj"
#define	_TAG_CHANNEL_ENABLECNTLINE	"EnableCntLine"
#define	_TAG_CHANNEL_ENABLESMOKEFIRE	"EnableSmokeFire"
#define _TAG_CHANNEL_DETECTIONPOINT	"DetectionPoint"
#define _TAG_CHANNEL_TRACKMODE		"TrackMode"
#define _TAG_CHANNEL_CURCLSGRP		"CurClsGrp"
#define _TAG_CHANNEL_METAFMT		"MetadataFormat"
#define _TAG_CHANNEL_RETRIGTIME		"RetrigTime"
#define _TAG_CHANNEL_MEAUNITS		"MeasurementUnits"
#define _TAG_CHANNEL_STATHOLDONTIME	"StatHoldonTime"
#define _TAG_CHANNEL_MINOBJAREA		"MinObjectArea"
#define _TAG_CHANNEL_ALARMDWELL		"AlarmDwell"
#define _TAG_CHANNEL_FADEOUTDWELL	"FadeoutDwell"
#define _TAG_CHANNEL_TOTALLICENSES	"TotalLicenses"
#define _TAG_CHANNEL_LICENSE_ID		"Id"
#define _TAG_CHANNEL_LICENSE		"License"

// XML Tags for license
#define _TAG_LICENSESETTINGS		"LicenseSettings"
#define _TAG_LICENSE_TOTALLICENSES	"TotalLicenses"
#define _TAG_LICENSE_LICENSE		"License"
#define _TAG_LICENSE_ID				"Id"
#define _TAG_LICENSE_DESC			"Desc"
#define _TAG_LICENSE_FEATURES		"Features"

// XML Tags for Zone Settings
#define _TAG_ZONESETTINGS		"ZoneSettings"
#define _TAG_TOTALZONES			"TotalZones"
#define _TAG_ZONE			"Zone"
#define _TAG_ZONE_ID			"Id"
#define _TAG_ZONE_NAME			"Name"
#define _TAG_ZONE_TYPE			"Type"
#define _TAG_ZONE_STYLE			"Style"
#define _TAG_ZONE_COLOR			"Color"
#define _TAG_ZONE_DISPLAY		"Display"
#define _TAG_ZONE_ENABLE		"Enable"
#define _TAG_ZONE_TOTALPOINTS		"TotalPoints"
#define _TAG_ZONE_POINT			"Point"
#define _TAG_ZONE_POINT_X		"X"
#define _TAG_ZONE_POINT_Y		"Y"

// XML Tags for Event Settings
#define _TAG_EVENTSETTINGS		"EventSettings"
#define _TAG_TOTALEVENTS		"TotalEvents"
#define _TAG_EVENT			"Event"
#define _TAG_EVENT_ID			"Id"
#define _TAG_EVENT_NAME			"Name"
#define _TAG_EVENT_TYPE			"Type"
#define _TAG_EVENT_NUMRULES		"NumRules"
#define _TAG_EVENT_ENABLE		"Enable"
#define _TAG_EVENT_RULE			"Rule"
#define _TAG_EVENT_RULE_LOGIC		"Logic"
#define _TAG_EVENT_RULE_TYPE		"RuleType"
#define _TAG_EVENT_RULE_ITOTALTRKOBJS	"iTotalTrkObjs"
#define _TAG_EVENT_RULE_TRKOBJ		"TrackingObject"
#define _TAG_EVENT_RULE_TRKOBJ_ID	"Id"
#define _TAG_EVENT_RULE_DATASIZE	"RuleDataSize"
#define _TAG_EVENT_RULE_DATA		"RuleData"

// XML Tags for Counter Settings
#define _TAG_COUNTERSETTINGS		"CounterSettings"
#define _TAG_TOTALCOUNTERS		"TotalCounters"
#define _TAG_COUNTER			"Counter"
#define _TAG_COUNTER_ID			"Id"
#define _TAG_COUNTER_NAME		"Name"
#define _TAG_COUNTER_DISPLAY		"Display"
#define _TAG_COUNTER_COLOR		"Color"
#define _TAG_COUNTER_ENABLE		"Enable"
#define _TAG_COUNTER_RESULT		"Result"
#define _TAG_COUNTER_NUMSUBCOUNTERS	"NumSubCounters"
#define _TAG_COUNTER_POINT		"Point"
#define _TAG_COUNTER_POINT_X		"X"
#define _TAG_COUNTER_POINT_Y		"Y"
#define _TAG_COUNTER_SUBCOUNTER		"SubCounter"
#define _TAG_COUNTER_SUBCOUNTER_ID	"Id"
#define _TAG_COUNTER_SUBCOUNTER_TYPE	"Type"
#define _TAG_COUNTER_SUBCOUNTER_TRIGID	"TrigId"
#define _TAG_COUNTER_SUBCOUNTER_ENABLE	"Enable"

// XML Tags for Calibration Settings
#define _TAG_CALIBRATIONSETTINGS	"CalibrationSettings"
#define _TAG_CALIBRATION		"Calibration"
#define _TAG_CALIBRATION_MODE		"Mode"
#define _TAG_CALIBRATION_TILTANGLE	"TiltAngle"
#define _TAG_CALIBRATION_ROLLANGLE	"RollAngle"
#define _TAG_CALIBRATION_PANANGLE	"PanAngle"
#define _TAG_CALIBRATION_CAMHEIGHT	"CamHeight"
#define _TAG_CALIBRATION_FOV		"FOV"

// XML Tags for Object Classification Settings
#define _TAG_OBJCLSSETTINGS		"ClassificationSettings"
#define _TAG_TOTALOBJCLS		"TotalClassifications"
#define _TAG_OBJCLS			"Classification"
#define _TAG_OBJCLS_ID			"Id"
#define _TAG_OBJCLS_NAME		"Name"
#define _TAG_OBJCLS_ENABLE		"Enable"
#define _TAG_OBJCLS_AREA		"Area"
#define _TAG_OBJCLS_AREA_LOW		"LowerThreshold"
#define _TAG_OBJCLS_AREA_HIGH		"UpperThreshold"
#define _TAG_OBJCLS_SPEED		"Speed"
#define _TAG_OBJCLS_SPEED_LOW		"LowerThreshold"
#define _TAG_OBJCLS_SPEED_HIGH		"UpperThreshold"
#define _TAG_OBJCLS_POSITION		"Position"

// XML Tags for Burnt-in annotation settings
#define _TAG_BIASETTINGS		"BIASettings"
#define _TAG_TOTALBIASTREAMS		"TotalBIASteams"
#define _TAG_BIA_ENABLE			"Enable"
#define _TAG_BIA_STREAM			"BIAStream"
#define _TAG_BIA_STREAM_ID		"Id"
#define _TAG_BIA_STREAM_NAME		"Name"
#define _TAG_BIA_STREAM_ENABLE		"Enable"
#define	_TAG_BIA_STREAM_DRAWINGFLAGS	"DrawingFlags"
#define _TAG_BIA_STREAM_ALARMCOLOR	"AlarmObjectColor"
#define _TAG_BIA_STREAM_NONALARMCOLOR	"NonAlarmObjectColor"
#define _TAG_BIA_STREAM_TXTSZOBJECT	"ObjectTextSize"
#define _TAG_BIA_STREAM_TXTSZCOUNTER	"CounterTextSize"
#define _TAG_BIA_STREAM_TXTSZSYSTEM	"SystemTextSize"

// XML Tags for Camera tamper detection settings
#define _TAG_TAMPERSETTINGS		"TamperDetectionSettings"
#define _TAG_TAMPER			"TamperDetection"
#define _TAG_TAMPER_ENABLE		"Enable"
#define _TAG_TAMPER_TIMEOUT		"AlarmTimeout"
#define _TAG_TAMPER_AREATHRESHOLD	"FiredAreaThreshold"
#define _TAG_TAMPER_LOWLIGHTENABLE	"LowLightEnable"

// XML Tags for Scene change detection settings
#define _TAG_SCENECHANGESETTINGS	"SceneChangeDetectionSettings"
#define _TAG_SCENECHANGE		"SceneChangeDetection"
#define _TAG_SCENECHANGE_MODE		"Mode"
#define _TAG_SCENECHANGE_TIMEOUT	"AlarmTimeout"
#define _TAG_SCENECHANGE_AREATHRESHOLD	"FiredAreaThreshold"

// XML Tags for PTZ tracking settings
#define _TAG_PTZSETTINGS		"PTZTrackingSettings"
#define _TAG_PTZ_			"PTZTracking"
#define _TAG_PTZ_ENABLE			"Enable"
#define _TAG_PTZ_HOMEPRESET		"HomePreset"
#define _TAG_PTZ_HOMETRACKINGONLY	"HomeTrackingOnly"
#define _TAG_PTZ_RETURN2HOME		"Return2Home"
#define _TAG_PTZ_RETURN2HOMETIMEOUT	"Return2HomeTimeout"
#define _TAG_PTZ_AT			"AutoTracking"
#define _TAG_PTZ_AT_ENABLE		"Enable"
#define _TAG_PTZ_AT_PROFILE		"Profile"
#define _TAG_PTZ_AT_MAXTRACKINGTIME	"MaxTrackingTime"
#define _TAG_PTZ_AT_HOLDONTIME		"HoldonTime"
#define _TAG_PTZ_AT_MANUALOVERRIDE	"ManualOverride"
#define _TAG_PTZ_AT_MANUALTIMEOUT	"ManualOverrideTimeout"
#define _TAG_PTZ_AT_TRIGGERBYRULE	"TriggerbyRule"
#define _TAG_PTZ_AT_RULE		"Rule"
#define _TAG_PTZ_AT_RULE_ID		"Id"

#endif // _vca_xmlcfgdef_h_

