//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DemoVCA.rc
//
#define IDR_MAINFRAME                   101
#define IDD_SIMPLEVCAAPP_DIALOG         102
#define IDD_VCADIALOG                   103
#define IDD_ZONESRULESCONFIGDLG         104
#define IDD_CONFIGPAGE                  105
#define IDD_TAMPERCONFIGPAGE            106
#define IDD_LICENSECONFIGPAGE           107
#define IDD_APPDLG                      108
#define IDC_TREELIST                    123
#define IDC_ALARMLIST                   124
#define IDD_VCASYSTEM_DIALOG            129
#define IDD_VCAENGINE_DIALOG            130
#define IDD_VCASETTING_DIALOG           131
#define IDD_ENGINE_SETTING_DIALOG       131
#define IDI_ICON10                      142
#define IDI_ICON1                       145
#define IDI_ICON_APPEAR                 146
#define IDI_ICON_TIMER                  147
#define IDI_ICON_COUNTER                148
#define IDI_ICON_DIRECTION              149
#define IDI_ICON_DISAPPEAR              150
#define IDI_ICON_ENTER                  151
#define IDI_ICON_EXIT                   152
#define IDI_ICON2                       155
#define IDI_ICON_PRESENCE               155
#define IDI_ICON_ZONE                   156
#define IDR_MENU1                       157
#define IDR_POPUPMENU                   157
#define IDR_MAIN_MENU                   160
#define IDB_GROUND                      163
#define IDB_BITMAP1                     165
#define IDB_CAMERA_SETUP                166
#define IDD_CLS_SETTING_DIALOG          167
#define IDD_ALARMVIWER_DIALOG           168
#define IDI_ICON_VEHICLE                169
#define IDD_RECORDING_DIALOG            170
#define IDI_ICON_CLUTTER                170
#define IDI_ICON_OBJFLT                 171
#define IDI_ICON_PERSON                 172
#define IDI_ICON_SPEED                  173
#define IDI_ICON_UNKNOWN                174
#define IDB_BITMAP2                     175
#define IDB_HATCH                       175
#define IDD_BLANK_DIALOG                176
#define IDD_DIALOG2                     180
#define IDD_ADVANCED_SETTING_DIALOG     181
#define IDD_DIALOG_LICENSE              182
#define IDD_PROGRESSDLG                 183
#define IDB_PROGRESS                    187
#define IDI_ICON3                       188
#define IDD_WAITDIALOG                  189
#define IDD_CONFIGAPP_DIALOG            190
#define IDD_CONFIG_DIALOG               191
#define IDD_CALIBRATIONCONFIGDLG        192
#define IDD_CALIBRATIONCTL              193
#define IDD_SCENECHANGECONFIGPAGE       194
#define IDB_BITMAP3                     197
#define IDB_NOSIGNAL                    197
#define IDI_ICON_TAMPER                 198
#define IDI_ICON_ABOBJ                  200
#define IDI_ICON_RMOBJ                  201
#define IDI_ICON_LINECOUNTER            202
#define IDI_ICON_GOP                    203
#define IDI_ICON_TAILGATING             210
#define IDI_ICON_FIRE                   211
#define IDI_ICON_SMOKE                  212
#define IDI_ICON_COLSIG                 213
#define IDB_BITMAP4                     214
#define IDB_RULER                       214
#define IDC_STATIC_DIALOG               1000
#define IDC_STATIC_ALARM                1001
#define IDC_BUTTON1                     1002
#define IDC_BUTTON_APPLY                1002
#define IDC_BTN_FILEOPEN                1002
#define IDC_CONFIG_EXIT                 1002
#define IDC_BN_CALIB_PAUSE              1002
#define IDC_BUTTON_ASSIGN               1002
#define IDC_BUTTON_LICENSE_FILE         1002
#define IDC_BTN_EXPORT                  1002
#define IDC_BTN_VLCPATHOPEN             1003
#define IDC_BUTTON_APPLY2               1003
#define IDC_BUTTON_RESTORE              1003
#define IDC_BUTTON2                     1003
#define IDC_CONFIG_APPLY                1003
#define IDC_BTN_ADD                     1003
#define IDC_BUTTON_REMOVE               1003
#define IDC_BUTTON_ADJUST               1004
#define IDC_ED_RAWFILEPATH              1005
#define IDC_BUTTON_UNCALIBRATE2         1005
#define IDC_BUTTON_UNCALIBRATE          1005
#define IDC_COMBO_VIDEOFORMAT           1006
#define IDC_COMBO_COLORFORMAT           1007
#define IDC_COMBO_CHANNEL               1008
#define IDC_BTN_OK                      1009
#define IDC_BTN_CANCEL                  1010
#define IDC_COMBO_RESOLUTION            1011
#define IDC_COMBO_CHANNEL2              1012
#define IDC_COMBO_BOARDNO               1012
#define IDC_ED_RAWFILEPATH2             1013
#define IDC_ED_STREAMPATH               1013
#define IDC_ED_RAWFILEPATH3             1014
#define IDC_ED_VLCEXEFILEPATH           1014
#define ID_BTN_APPLY                    1015
#define IDC_RADIO2                      1023
#define IDC_RADIO_CAP5                  1023
#define IDC_RADIO_FILE                  1023
#define IDC_RADIO_RAWFILE               1024
#define IDC_COMBO_FRAMERATE_CAP5        1029
#define IDC_CAM_SETUP                   1030
#define IDC_HEIGHT                      1031
#define IDC_TILTANGLE                   1032
#define IDC_TILT                        1032
#define IDC_ED_HEIGHT                   1033
#define IDC_ED_TILT                     1034
#define IDC_CAMERA_SETUP_INFO           1035
#define IDC_METER                       1036
#define IDC_DEG                         1037
#define IDC_ED_FOV                      1038
#define IDC_DEG1                        1039
#define IDC_FOV                         1040
#define IDC_INTRICSIC_PARAM             1041
#define IDC_FOV_SLIDER                  1042
#define IDC_BUTTON_PAUSE                1043
#define IDC_ED_HEIGHT2                  1043
#define IDC_ADV_PARAM                   1044
#define IDC_PAN                         1045
#define IDC_CLASSIFIER_LIST             1046
#define IDC_ED_PAN                      1046
#define IDC_BTN_REMOVE                  1047
#define IDC_PAN_SLIDER                  1047
#define IDC_ED_NAME                     1048
#define IDC_DEG2                        1048
#define IDC_ED_MINAREA                  1049
#define IDC_ROLL                        1049
#define IDC_COMBO_ENABLE                1050
#define IDC_ED_ROLL                     1050
#define IDC_ED_MINSPEED                 1051
#define IDC_PAN_SLIDER2                 1051
#define IDC_ROLL_SLIDER                 1051
#define IDC_ED_MAXSPEED                 1052
#define IDC_DEG3                        1052
#define IDC_ED_MAXAREA                  1053
#define IDC_BTN_APLLY                   1054
#define IDC_BTN_APPLY                   1054
#define IDC_CHECK1                      1055
#define IDC_CHECK_PAUSE                 1055
#define IDC_CHECK_CAMSTAB_ENABLE        1055
#define IDC_BTN_RESET                   1055
#define IDC_CHECK_ROI                   1055
#define IDC_BTN_APPLY2                  1056
#define IDC_STATIC_CALI_STATUS          1056
#define IDC_CHECK_OBTRACKING_ENABLE     1056
#define IDC_BTN_PREV                    1057
#define IDC_MEASUREMENT_PARAM           1057
#define IDC_CHECK_ABRM_ENABLE           1057
#define IDC_BTN_NEXT                    1058
#define IDC_CALIB_UNITS_COMBO           1058
#define IDC_CHECK_CNTLINE_ENABLE        1058
#define IDC_CHECK_ENABLE                1059
#define IDC_CHECK_TAMPER                1059
#define IDC_EDIT1                       1060
#define IDC_ALARM_HOLDOFF_EDIT          1060
#define IDC_RETRIGGER_TIME_EDIT         1060
#define IDC_EDIT_HWGUID                 1060
#define IDC_EDIT_ROI_X                  1060
#define IDC_EDIT_SCENE_WARNING          1060
#define IDC_ED_FILENAME                 1061
#define IDC_TAMPER_TIME_EDIT            1061
#define IDC_EDIT_ROI_Y                  1061
#define IDC_EDIT_PATH                   1062
#define IDC_EDIT_                       1062
#define IDC_TAMPER_AREA_EDIT            1062
#define IDC_EDIT_ROI_W                  1062
#define IDC_EDIT_PERIOD                 1063
#define IDC_CHECK_SUPPRESS_LIGHT        1063
#define IDC_EDIT4                       1063
#define IDC_EDIT_ROI_H                  1063
#define IDC_EDIT_MARGINE                1064
#define IDC_RADIO_VLC                   1064
#define IDC_CHECK_DN_COLOR              1064
#define IDC_RADIO_DSHOW                 1065
#define IDC_CHECK_DN_RIM                1065
#define IDC_RADIO_NOT_SOURCE            1066
#define IDC_COMBO_DEVICENUM_DSHOW       1068
#define IDC_RADIO6                      1072
#define IDC_RADIO7                      1073
#define IDC_STATIC_LICENSE_INFO_1       1074
#define IDC_EDIT_LICENSE                1075
#define IDC_EDIT_LICENSE_DIRECT         1075
#define IDC_STATIC_LICENSE_INFO_2       1076
#define IDC_EDIT_LICENSE2               1077
#define IDC_EDIT_LICENSE_FILE           1077
#define IDC_STATIC_VIDEO                1081
#define IDC_CONFIG_TAB                  1082
#define IDC_CALIB_STATUS_GROUP          1083
#define IDC_RAW_GROUP                   1084
#define IDC_VIDEO_PREVIEW               1085
#define IDC_STATIC_LICENSE              1086
#define IDC_BTN_LICENSE_REGISTER        1087
#define IDC_BTN_LICENSE_REMOVE          1088
#define IDC_COMBO1                      1091
#define IDC_COMBO_ENGINE                1091
#define IDC_COMBO_VIDEO_ROTATE          1091
#define IDC_LICENSE_CONFIG_LIST         1092
#define IDC_LICENSE_CONFIG_LIST2        1093
#define IDC_LICENSE_CONFIG_LIST_ENGINE  1093
#define IDC_COMBO2                      1093
#define IDC_COMBO_FRAME_TYPE            1093
#define IDC_EDIT_OBJSIZE                1094
#define IDC_EDIT_OBJHOLDTIME            1095
#define IDC_RADIO_DIRECT                1096
#define IDC_CHECK_SMOKEFIRE_ENABLE      1097
#define IDC_PROGRESS_EXPORT             1098
#define IDC_RADIO_DETECTPOINT1          1099
#define IDC_RADIO_DETECTPOINT2          1100
#define IDC_RADIO_DETECTPOINT3          1101
#define IDC_RADIO_DISABLE               1102
#define IDC_RADIO_SURVEILLANCE          1102
#define IDC_RADIO_AUTOMATIC             1103
#define IDC_RADIO_PEOPLE                1103
#define IDC_RADIO_MANUAL                1104
#define ID_CALIB_RULER                  2000
#define ID_CALIB_SKY                    2001
#define ID_CALIB_TRANS_GRID             2002
#define ID_CALIB_INSERT_OBJECT          2003
#define ID_CONTEXTMENU_CLEARITEM        32760
#define ID_CONTEXTMENU_CLEARALLITEMS    32761
#define ID_Menu                         32762
#define ID_ADDZONE                      32771
#define ID_ADDLINE                      32772
#define ID_REMOVEZONE                   32773
#define ID_REMOVEZONES                  32774
#define ID_ADDNODE                      32775
#define ID_REMOVENODE                   32776
#define ID_ADDCOUNTER                   32777
#define ID_REMOVECOUNTER                32778
#define ID_RESETCOUNTER                 32779
#define ID_REMOVECOUNTERS               32780
#define ID_RESETCOUNTERS                32781
#define ID_SAVETOFILE                   32782
#define ID_LOADFROMFILE                 32783

#define ID_PRESENCE                     32791
#define ID_ENTER                        32792
#define ID_EXIT                         32793
#define ID_APPEAR                       32794
#define ID_DISAPPEAR                    32795
#define ID_STOP                         32796
#define ID_DWELL                        32797
#define ID_DIRECTION                    32798
#define ID_SPEED                        32799
#define ID_AREA                         32800
#define ID_TAILGATING                   32801
#define ID_ABANDONREMOVE                32802
#define ID_LINECOUNTER_A                32803
#define ID_LINECOUNTER_B                32804
#define ID_RMOBJ                        32805
#define ID_COLOR_FILTER                 32806
#define ID_SMOKE                        32807
#define ID_FIRE                         32808
#define ID_CONTROL_START                32809
#define ID_CONTROL_EXIT                 32810
#define ID_CONTROL_RESTART              32811
#define ID_TOOLS_LICENSEACTIVATION      32812
#define ID_DISPLAY_BLOBS                32813
#define ID_DISPLAY_NON_ALARMS           32814
#define ID_DISPLAY_TARGETID             32815
#define ID_DISPLAY_OBJECTHEIGHT         32816
#define ID_DISPLAY_OBJECTSPEED          32817
#define ID_DISPLAY_OBJECTAREA           32818
#define ID_DISPLAY_OBJECTCLASSIFICATION 32819
#define ID_DISPLAY_OBJECTCOLORSIGNATURE 32820
#define ID_DISPLAY_TAMPER_ALARM         32821
#define ID_VCASETTING                   32824
#define ID_ENGINESETTING                32825
#define ID_CALIBRATIONSETTING           32826
#define ID_CLASSIFICATIONSETTING        32827
#define ID_ADVANCEDSETTING              32830
#define ID_SAVE_NVE_CONFIGURE           32831
#define ID_LOAD_NVE_CONFIGURE           32833
#define ID_VIEWLICENSEINFO              32834
#define ID_OPTION_RECORDING             32835
#define ID_OPTION_SAVE_CURRENT_SETTING  32836
#define ID_OBJECT_CLASS                 32837
#define ID_IMPORT_CONFIG                32838
#define ID_CONTEXTMENU_SAVEALARMSTOCSV  32838
#define ID_EXPORT_CONFIG                32839
#define ID_CONFIG_MODE                  32840
#define ID_CONTEXTMENU_EXPORTTOAVI      32841

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        215
#define _APS_NEXT_COMMAND_VALUE         32842
#define _APS_NEXT_CONTROL_VALUE         1103
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
